### ISSUE TITLE
Can you provide an example of associating "std:: net:: UdpSocket"?

### ISSUE THREAD

**Issue by yunfengwangluo** [Matrix-Zhang/kcp#20]
Thank you very much for your project, but I have referred to many different codes and still don't understand how to associate it with "std:: net:: UdpSocket". If your time permits and you are willing to provide a simple association to "std:: net:: UdpSocket", it will be of great help to me! Thank you again!

**Comment by zonyitoo** [comment]
```rust
struct SocketWrapper(UdpSocket);

impl std::io::Write for SocketWrapper {
    // ... write() calls UdpSocket.send()
}

let socket: UdpSocket = ...;
let kcp = Kcp::new(1234, SocketWrapper(socket));
```

**Comment by miaomiao1992** [comment]
very nice
