### ISSUE TITLE
After reading data 128 times, kcp.recv will report an error

### ISSUE THREAD

**Issue by yunfengwangluo** [Matrix-Zhang/kcp#21]
Err` value: RecvQueueEmpty
`usize                        123
usize                        124
usize                        125
usize                        126
usize                        127
usize                        128
thread 'main' panicked at src/bin/conn2.rs:36:42:
called `Result::unwrap()` on an `Err` value: RecvQueueEmpty`

I have conducted a simple investigation and it should be related to "const KCP_WND.RCV: u16=128;//must>=max fragment size", but this should not be an error. Is there a method to set it? I tried to modify this value to 500 The number of reads can exceed 128, but this should not be the method to fix this problem. At the same time, we also encountered a new issue where "kcp. set_wndsize (256, 256);" still outputs the same error at 256.

I wonder if I need to set certain values to avoid this issue, or if this is an unnoticed error?

**Comment by zonyitoo** [comment]
This `Err` indicates that there was nothing could be `recv()`ed from KCP, which is very similar to `EAGAIN` in POSIX's `recv()`. I don't think that is an issue.
